### ISSUE TITLE
Support for %% comments

### ISSUE THREAD

**Issue by dietmarw** [MSzturc/obsidian-advanced-slides#81] opened 2022-05-11 10:47 UTC
It looks like the Advanced Slides plugin does not recognise [`%%` comment section](https://help.obsidian.md/How+to/Format+your+notes#Comments). They work with the built in presentation view but not with the Advanced presentation.

**Comment by MSzturc** [comment] 2022-05-11 10:54
Im not able to reproduce it. Can you provide me an sample?

I've tested it with the sample from here: https://mszturc.github.io/obsidian-advanced-slides/basic-syntax/textstyle/

**Comment by dietmarw** [comment] 2022-05-11 11:00
Looks like inline comments are supported but not multiline in the shape:
```md
Here a multi-line comment:

%%
several lines
that should not be shown in the presentation
%%

Should appear again
```

**Comment by MSzturc** [comment] 2022-05-11 11:07
Ohh yeah correct. Will be fixed in the upcoming release

**Closed** 2022-05-11 21:15 UTC
