### ISSUE TITLE
New Obsidian Release 0.16.0 breaks a great deal in Advanced Slides

### ISSUE THREAD

**Issue by stoweboyd** [MSzturc/obsidian-advanced-slides#129] opened 2022-08-30 20:34 UTC
**Describe the bug**
Various settings like the styling of headers, uses of various element classes, and the correct rendering of CSS no longer work as previously. 

**Samples to Reproduce**
Try it on various sample themes. I have been using css/mattropolis.css, which no longer works as before.

**Comment by MSzturc** [comment] 2022-08-30 20:38
Yeah, i've noticed that too, but since im a bit busy in the next few weeks and most of my plugins i use are a bit buggy with 0.16 ive decided to update a bit later.

**Comment by stoweboyd** [comment] 2022-08-30 20:57
> Yeah, i've noticed that too, but since im a bit busy in the next few weeks and most of my plugins i use are a bit buggy with 0.16 ive decided to update a bit later.

I may back out of 016.0 if various plugins don't work... I'm giving that talk in October, so I have a month to wait.

**Comment by MSzturc** [comment] 2022-08-30 22:17
Yeah, was a bit out of nowhere, and than with so much (breaking) changes, i guess many themes and many plugins will behave in the next few days not as they should and since my vault is the based of my dayjob it has to work, so i will start to migrate to 0.16 when 0.16.2 or 0.16.3 was released :-)

**Comment by stoweboyd** [comment] 2022-10-05 19:32
Obsidian has pushed out v0.16.3. I may have to move my upcoming slide shows to some other platform than Advanced Slides.

**Comment by MSzturc** [comment] 2022-10-05 21:30
Yeah I know but as long as 0.16 is still an insider build i wont be able to update for a couple of reasons:
1. Moving to a new version of advanced slides would exclude most of the users since only <5% of the users are Obsidian supporters
2. The changes needed are not backwards compatible, so updating advanced slides to a newer version would mean that i have to support two versions since the majority of users are still on 0.15, what im not able to since i dont have the needed time.
3. Supporting multiple versions means to be able to run Obsidian 0.15 and 0.16 in parallel which is not trivial. It would need much time build up the infrastructure to do this.

Im pretty disappointed of the update policy the obsidian devs do since this feature gap you feel right now is unnessesary in my point of view. In my opinion 0.16.4 is stable enough to make it public and i dont understand why they keep hiding it behind the insider paywall.

**Comment by ebullient** [comment] 2022-10-11 02:03
I've been able to get *some* things working with 0.16.x, but yes... not everything works exactly as you might expect (and backgrounds are gone).

How can I help? Is there something I can look at that would help me understand what has to be changed for 0.16? You could take advantage of BRAT... leave a published branch for 0.15.x compat, and use BRAT releases for 0.16?

Anyway, I use this a lot, have a missing background issue that I would like to figure out, and would be happy to help (I also have a day job, so, some pointers are appreciated, but I won't be overwhelming you with questions. ;) )

**Comment by MSzturc** [comment] 2022-10-14 08:21
Today i've updated to Obsidian v1.0.0. I've noticed 2 bugs:
- The Preview window opens in a new Tab, i should split the window instead
- The synchronisation of source and slide has a couple issues

There are no rendering issues on my side, all my slides look as they should look on the default Obsidian Theme without css scripts.

Can you provide samples to reproduce you issues?

**Comment by ebullient** [comment] 2022-10-14 12:21
The new tab behavior is fine (it works really well with stacking.. the split would not). I'm not sure if there is a default (new split or new tab) that you could check? Or.. provide 3 new commands: New split, new tab, new popout window..

**Comment by stoweboyd** [comment] 2022-10-15 11:26
I've upgraded as well, but all the problems I reported are still there.
[paradoxes slideshow.md](https://github.com/MSzturc/obsidian-advanced-slides/files/9791903/paradoxes.slideshow.md)

**Comment by MSzturc** [comment] 2022-10-15 18:24
Ahhh now I understand!
I did some code cleanup that causes this rendering issues. Will be fixed with 1.18

**Comment by MSzturc** [comment] 2022-10-15 21:09
Please retest with 1.18

**Comment by stoweboyd** [comment] 2022-11-03 10:52
Seems to be working, now!

**Closed** 2022-11-03 14:20 UTC
Labels: bug
